// REFAL-AGENT-015 — generates docs/refal-agent-scenario-matrix.md from the
// single source of truth in src/agentScenarios.js. Re-runs every scenario
// (same fakes/stubs as the test file — no real network/model/calendar
// access) so the report can never drift from what actually passed/failed.
//
// Usage: node scripts/generateScenarioMatrixReport.js

const fs = require("node:fs");
const path = require("node:path");
const { SCENARIOS, runScenario } = require("../src/agentScenarios");

const OUT_PATH = path.join(__dirname, "..", "docs", "refal-agent-scenario-matrix.md");

const CATEGORY_LABEL = {
  information: "A — Information / RAG",
  memory: "B — Context / Memory",
  clarification: "C — Clarification",
  handover: "D — Handover / Consent",
  booking: "E — Booking",
  safety: "F — Safety / Policy",
  language: "G — Language",
  resilience: "H — Failures / Resilience"
};

function localeLabel(locale) {
  if (locale === "english") return "EN";
  if (locale === "arabic") return "AR";
  if (locale === "greek") return "EL";
  return locale;
}

async function main() {
  const rows = [];
  for (const scenario of SCENARIOS) {
    let outcome = "run_error";
    let failures = [];
    let observed = null;
    try {
      const run = await runScenario(scenario);
      outcome = run.observed.result?.outcome ?? "n/a";
      failures = run.failures;
      observed = run.observed;
    } catch (error) {
      failures = [`threw: ${String(error?.message || error)}`];
    }
    const passed = failures.length === 0;
    rows.push({ scenario, outcome, failures, passed, observed });
  }

  const total = rows.length;
  const passedCount = rows.filter((r) => r.passed).length;
  const knownFailures = rows.filter((r) => !r.passed && r.scenario.knownFailure);
  const unexpectedFailures = rows.filter((r) => !r.passed && !r.scenario.knownFailure);
  const localeCounts = rows.reduce((acc, r) => { const key = localeLabel(r.scenario.locale); acc[key] = (acc[key] || 0) + 1; return acc; }, {});
  const featureCounts = rows.reduce((acc, r) => {
    for (const tag of r.scenario.featureTags || []) acc[tag] = (acc[tag] || 0) + 1;
    return acc;
  }, {});

  const byCategory = new Map();
  for (const row of rows) {
    const cat = row.scenario.category;
    if (!byCategory.has(cat)) byCategory.set(cat, []);
    byCategory.get(cat).push(row);
  }

  const lines = [];
  lines.push("# REFAL Agent Scenario Matrix (REFAL-AGENT-015)");
  lines.push("");
  lines.push("Generated by `scripts/generateScenarioMatrixReport.js` from the single");
  lines.push("source of truth in `src/agentScenarios.js` — every scenario listed here");
  lines.push("was actually re-run against the real Agent-runtime boundary");
  lines.push("(`runAgentTurnForContact`/`runAgentTurn` + the real `TOOL_REGISTRY`) with");
  lines.push("scripted decisions and in-memory fakes; nothing here touches a real");
  lines.push("customer, Google Calendar, WhatsApp, or production Supabase data.");
  lines.push("");
  lines.push("**This is scenario coverage with measurable expected outcomes, not the");
  lines.push("quality benchmark** — REFAL-AGENT-016 uses this matrix (plus Ticket 013's");
  lines.push("telemetry) to calculate quality metrics against real model decisions.");
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(`- Total scenarios: **${total}**`);
  lines.push(`- Passed: **${passedCount}**`);
  lines.push(`- Known failures (tied to a filed ticket): **${knownFailures.length}**`);
  lines.push(`- Unexpected failures: **${unexpectedFailures.length}**`);
  lines.push(`- Locale distribution: ${Object.entries(localeCounts).map(([k, v]) => `${k}=${v}`).join(", ")}`);
  lines.push(`- Feature distribution: ${Object.entries(featureCounts).sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k}=${v}`).join(", ")}`);
  if (knownFailures.length) {
    lines.push("");
    lines.push("### Known failures");
    for (const row of knownFailures) lines.push(`- **${row.scenario.id}** blocked by \`${row.scenario.knownFailure.ticket}\`: ${row.scenario.knownFailure.note}`);
  }
  if (unexpectedFailures.length) {
    lines.push("");
    lines.push("### ⚠ Unexpected failures (not tied to a known ticket — investigate)");
    for (const row of unexpectedFailures) lines.push(`- **${row.scenario.id}**: ${row.failures.join("; ")}`);
  }
  lines.push("");

  for (const [category, categoryRows] of byCategory) {
    lines.push(`## ${CATEGORY_LABEL[category] || category}`);
    lines.push("");
    lines.push("| ID | Locale | Description | Tools expected | Status | Dependency |");
    lines.push("|---|---|---|---|---|---|");
    for (const row of categoryRows) {
      const s = row.scenario;
      const tools = (s.expected?.toolsInclude || []).join(", ") || "—";
      const status = row.passed ? "✅ pass" : (s.knownFailure ? "🟡 known failure" : "❌ UNEXPECTED FAIL");
      const dependency = s.knownFailure ? s.knownFailure.ticket : "—";
      const desc = s.description.replace(/\|/g, "\\|");
      lines.push(`| ${s.id} | ${localeLabel(s.locale)} | ${desc} | ${tools} | ${status} | ${dependency} |`);
    }
    lines.push("");
  }

  fs.writeFileSync(OUT_PATH, lines.join("\n") + "\n", "utf8");
  console.log(`Wrote ${OUT_PATH}`);
  console.log(`${passedCount}/${total} passed, ${knownFailures.length} known failures, ${unexpectedFailures.length} unexpected failures.`);
  if (unexpectedFailures.length) process.exitCode = 1;
}

main().catch((error) => { console.error(error); process.exitCode = 1; });
