// REFAL-AGENT-016 — builds docs/refal-agent-benchmark.md's markdown content
// from an already-computed aggregate (src/benchmarkScorer.js's output).
// Pure string building — no I/O here, so it's directly testable and can
// never silently divide by zero (every rate is pre-computed as
// {rate, numerator, denominator} by the scorer, and `rate: null` is always
// rendered as "n/a", never as a NaN or a crash).

function fmtRate(rateObj) {
  if (!rateObj || rateObj.rate === null) return "n/a (0 evaluable)";
  return `${(rateObj.rate * 100).toFixed(1)}% (${rateObj.numerator}/${rateObj.denominator})`;
}

function fmtNum(value, digits = 1) {
  return typeof value === "number" && Number.isFinite(value) ? value.toFixed(digits) : "n/a";
}

function table(headers, rows) {
  const lines = [`| ${headers.join(" | ")} |`, `|${headers.map(() => "---").join("|")}|`];
  for (const row of rows) lines.push(`| ${row.join(" | ")} |`);
  return lines.join("\n");
}

function metricRows(legacyAgg, agentAgg) {
  const keys = [
    ["currentRequestAnsweredRate", "Current request answered"],
    ["unnecessaryQuestionRate", "Unnecessary questions"],
    ["unnecessaryToolCallRate", "Unnecessary tool calls"],
    ["genericFallbackRate", "Generic fallback"],
    ["languageMismatchRate", "Language mismatch"],
    ["toolFailureRate", "Tool failure"],
    ["unsafeFinalResponseRate", "Unsafe final response (delivered — gates readiness)"],
    ["unsafeDraftBlockedRate", "Unsafe draft blocked pre-delivery (informational only)"]
  ];
  return keys.map(([key, label]) => {
    const l = legacyAgg?.metrics?.[key];
    const a = agentAgg?.metrics?.[key];
    const delta = l?.rate !== null && a?.rate !== null && l?.rate !== undefined && a?.rate !== undefined
      ? `${((a.rate - l.rate) * 100).toFixed(1)} pp`
      : "n/a";
    return [label, fmtRate(l), fmtRate(a), delta];
  });
}

function localeTable(breakdown) {
  return Object.entries(breakdown || {}).map(([locale, data]) => [
    locale, data.total, data.measured, fmtRate(data.currentRequestAnsweredRate), fmtRate(data.unnecessaryQuestionRate), fmtRate(data.languageMismatchRate), fmtRate(data.fallbackRate)
  ]);
}

function featureTable(breakdown) {
  return Object.entries(breakdown || {}).map(([feature, data]) => [
    feature, data.total, data.measured, fmtRate(data.currentRequestAnsweredRate), fmtRate(data.fallbackRate)
  ]);
}

function distributionRows(dist) {
  return Object.entries(dist || {}).sort((a, b) => b[1] - a[1]).map(([key, count]) => [key, count]);
}

function buildReportMarkdown({ environment, legacy, agent, legacyExcluding, agentExcluding, historical, cost, readiness }) {
  const lines = [];
  lines.push("# REFAL Agent Benchmark (REFAL-AGENT-016)");
  lines.push("");
  lines.push("Legacy-vs-Agent quality comparison. Generated by `scripts/runAgentBenchmark.js`");
  lines.push("from `src/benchmarkScenarios.js` (reusing REFAL-AGENT-015's scenario IDs) — see");
  lines.push("that file for exactly which messages were sent and which scenarios were excluded");
  lines.push("as pure implementation-mechanics (not a model-decision-quality signal).");
  lines.push("");
  lines.push("## Environment");
  lines.push("");
  lines.push(`- Date: ${environment.date}`);
  lines.push(`- Branch: ${environment.branch}`);
  lines.push(`- Commit: ${environment.commit}`);
  lines.push(`- Model (Agent decision): ${environment.model}`);
  lines.push(`- Evaluator model: ${environment.evaluatorModel}`);
  lines.push(`- Provider: ${environment.provider}`);
  lines.push(`- Scenario count: ${environment.scenarioCount}`);
  lines.push(`- Runs per scenario: ${environment.runsPerScenario}`);
  lines.push(`- Max Agent steps: ${environment.maxSteps}`);
  if (environment.note) lines.push(`- Note: ${environment.note}`);
  lines.push("");

  lines.push("## Overall comparison (raw — includes known-open-ticket-affected turns)");
  lines.push("");
  lines.push(table(["Metric", "Legacy", "Agent", "Delta (Agent - Legacy)"], metricRows(legacy, agent)));
  lines.push("");
  lines.push(`- Legacy: ${legacy.totals.measured} measured / ${legacy.totals.notMeasurable} not measurable / ${legacy.totals.infrastructureErrors} infrastructure errors (of ${legacy.totals.total})`);
  lines.push(`- Agent: ${agent.totals.measured} measured / ${agent.totals.notMeasurable} not measurable / ${agent.totals.infrastructureErrors} infrastructure errors (of ${agent.totals.total})`);
  lines.push("");

  lines.push("## Overall comparison (excluding known-open-ticket-affected turns)");
  lines.push("");
  lines.push(table(["Metric", "Legacy", "Agent", "Delta (Agent - Legacy)"], metricRows(legacyExcluding, agentExcluding)));
  lines.push("");

  lines.push("## Per-language results (Agent arm)");
  lines.push("");
  lines.push(table(["Locale", "Total", "Measured", "Answered", "Unnecessary Qs", "Lang. mismatch", "Fallback"], localeTable(agent.localeBreakdown)));
  lines.push("");
  lines.push("## Per-language results (Legacy arm)");
  lines.push("");
  lines.push(table(["Locale", "Total", "Measured", "Answered", "Unnecessary Qs", "Lang. mismatch", "Fallback"], localeTable(legacy.localeBreakdown)));
  lines.push("");

  lines.push("## Per-feature results (Agent arm)");
  lines.push("");
  lines.push(table(["Feature", "Total", "Measured", "Answered", "Fallback"], featureTable(agent.featureBreakdown)));
  lines.push("");

  lines.push("## Fallback reason distribution");
  lines.push("");
  lines.push("Agent:");
  lines.push(table(["Reason", "Count"], distributionRows(agent.fallbackReasonDistribution)));
  lines.push("");
  lines.push("Legacy:");
  lines.push(table(["Reason", "Count"], distributionRows(legacy.fallbackReasonDistribution)));
  lines.push("");

  lines.push("## Response-policy rejection reason-code distribution (Agent arm)");
  lines.push("");
  lines.push(table(["Reason code", "Count"], distributionRows(agent.rejectionReasonDistribution)));
  lines.push("");

  lines.push("## Tool usage distribution (Agent arm)");
  lines.push("");
  lines.push(table(["Tool", "Count"], distributionRows(agent.toolUsageDistribution)));
  lines.push("");

  lines.push("## RAG status distribution (Agent arm)");
  lines.push("");
  lines.push(table(["Status", "Count"], distributionRows(agent.ragStatusDistribution)));
  lines.push("");

  lines.push("## Agent step statistics");
  lines.push("");
  lines.push(`- Mean: ${fmtNum(agent.stepStats.mean, 2)}`);
  lines.push(`- Median: ${fmtNum(agent.stepStats.median, 1)}`);
  lines.push(`- Max: ${agent.stepStats.max ?? "n/a"} (MAX_AGENT_STEPS = ${environment.maxSteps})`);
  lines.push(`- Scenarios that hit the max step count: ${agent.scenariosAtMaxSteps.length ? agent.scenariosAtMaxSteps.join(", ") : "none"}`);
  lines.push("");

  lines.push("## Known-open-ticket-affected turns");
  lines.push("");
  if (agent.knownTicketAffected.length === 0 && legacy.knownTicketAffected.length === 0) {
    lines.push("None.");
  } else {
    lines.push(table(["Scenario", "Arm", "Run", "Ticket", "Reason"], [...legacy.knownTicketAffected, ...agent.knownTicketAffected].map((k) => [k.scenarioId, k.arm, k.runIndex, k.ticket, k.reason])));
  }
  lines.push("");

  lines.push("## Unexpected failures (not tied to a known ticket)");
  lines.push("");
  const unexpected = [...legacy.unexpectedFailures, ...agent.unexpectedFailures];
  if (unexpected.length === 0) {
    lines.push("None.");
  } else {
    lines.push(table(["Scenario", "Arm", "Run", "Outcome", "rejectionReasonCodes"], unexpected.map((u) => [u.scenarioId, u.arm, u.runIndex, u.outcome, (u.metrics?.rejectionReasonCodes || []).join(",") || "—"])));
  }
  lines.push("");

  if (historical) {
    lines.push("## Historical context (NOT the same experiment — labeled separately)");
    lines.push("");
    lines.push("HISTORICAL (pre-refactor synthetic measurement, cited in docs/refal-agent-refactor-progress.md):");
    lines.push(`- ${historical}`);
    lines.push("");
    lines.push("CURRENT BENCHMARK: see the tables above. These two datasets use different");
    lines.push("scenario sets, different measurement methods, and are not directly comparable");
    lines.push("as percentages — cited for context only.");
    lines.push("");
  }

  lines.push("## Cost report");
  lines.push("");
  lines.push(`- Total Agent decision model calls attempted: ${cost.totalCalls}`);
  lines.push(`- Successful calls: ${cost.successfulCalls}`);
  lines.push(`- Failed calls (infrastructure): ${cost.failedCalls}`);
  lines.push(`- Average calls per scenario: ${fmtNum(cost.avgCallsPerScenario, 2)}`);
  lines.push(`- Total Agent steps across all runs: ${cost.totalSteps}`);
  lines.push(`- Retries observed: ${cost.retries}`);
  lines.push(`- Token usage: ${cost.tokenUsageAvailable ? `${cost.promptTokens} prompt / ${cost.completionTokens} completion` : "not available"}`);
  lines.push(`- Approximate cost (USD): ${cost.costAvailable ? `$${cost.costUsd.toFixed(4)}` : "not available"}`);
  lines.push("");

  lines.push("## Readiness assessment");
  lines.push("");
  lines.push(`**${readiness.category}**`);
  lines.push("");
  for (const point of readiness.evidence) lines.push(`- ${point}`);
  lines.push("");

  return lines.join("\n") + "\n";
}

module.exports = { buildReportMarkdown, fmtRate, fmtNum, table };
