"use strict";

// P3.9 / W3.9.1-W3.9.6 — the fact catalogue. One row per MB fact.
//
// WHY THIS FILE EXISTS
// --------------------
// brainFactMap says WHICH topic must state a fact. It never says WHAT the fact
// actually asserts. That text lived only in docs/brain/SOURCE-ANALYSIS.md and in
// the Arabic manual, so nothing executable could check a claim, and no reviewer
// could be handed a single sentence to approve or reject.
//
// This module is that missing layer: the literal claim text, its provenance, and
// every number it asserts. src/factRegister.js turns each row into a register
// row (claim_text + trust tier + review cadence), so the shape here is a
// contract. Adding, renaming or dropping a field breaks the register.
//
// WHY EVERY NUMBER NEEDS A ROW (W3.9.2)
// -------------------------------------
// MB module 2 opens with the only rule that matters here: every number is a hard
// fact that must never be invented, approximated, or stated without approved
// evidence. A number with no register row is a number nobody owns, nobody
// re-verifies, and nobody can expire. So `numbers` is exhaustive and literal:
// every numeric literal a claim asserts gets an entry, even when the figure also
// appears in the claim text. 15% is not "roughly the corporate rate", it is a
// rate with an effective date that a reviewer re-checks against the authority.
//
// WHAT THE FIELDS MEAN
// --------------------
// claim          the assertion as REFAL would state it. Plain text, no markdown,
//                no connector dash (anti-regression 0.2). For a fact that is a
//                RULE, the claim states what REFAL does or refuses to do.
// sourceType     who a reviewer must re-verify against. A legal statement that
//                merely arrives via the manual is still cy-authority or
//                foreign-authority, because the manual is not the authority.
// jurisdiction   the country the claim is ABOUT, not where it was written.
// numbers        every numeric literal the claim asserts.
// volatility     starts from the owning topic in brainTaxonomy, overridden per
// trustTier      fact where the fact is clearly different from its topic. Every
//                override carries its reason in `notes`.
// effectiveFrom  only when the source states a date. Never invented.
//
// THE PRICE IS NOT IN HERE. MB-F9 governs the formation package price and
// deliberately carries no figure: MB-DYN6 forbids freezing it, so the value is
// served from refal_offers_and_pricing at runtime (see FORBIDDEN_CORPUS_LITERALS
// in brainFactMap). The same applies to every MB-DYN row.

const ROWS = [
  // ------------------------------------------------ 6.2 company lifecycle
  {
    id: "MB-F1",
    topics: ["company-lifecycle"],
    claim: "A Cyprus company moves through ten stages: idea, incorporation, banking, tax, accounting, operations, growth, changes, renewal, closure.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.1 / SOURCE-ANALYSIS 6.2",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "explanatory",
    effectiveFrom: null,
    notes: "",
  },

  // ------------------------------------------- 6.3 the formation package
  {
    id: "MB-F2",
    topics: ["formation-package"],
    claim: "The Refalco formation package includes incorporation of a Cyprus Ltd through the full official procedures, usually completed in about two weeks once the customer's documents are complete.",
    sourceType: "refalco-commercial",
    sourceRef: "MB 2.1 / SOURCE-ANALYSIS 6.3",
    jurisdiction: "CY",
    numbers: [{ value: "about two weeks", kind: "duration" }],
    volatility: "VOLATILE",
    trustTier: "commercial",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F3",
    topics: ["formation-package"],
    claim: "The formation package includes reserving the company name and obtaining its approval from the Cyprus Registrar of Companies, which is the step that formally starts the commercial identity.",
    sourceType: "refalco-commercial",
    sourceRef: "MB 2.1 / SOURCE-ANALYSIS 6.3",
    jurisdiction: "CY",
    numbers: [],
    volatility: "VOLATILE",
    trustTier: "commercial",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F4",
    topics: ["formation-package"],
    claim: "The formation package includes preparing and attesting the incorporation documents, drafting the Memorandum and Articles of Association and filing them so the file is not rejected administratively.",
    sourceType: "refalco-commercial",
    sourceRef: "MB 2.1 / SOURCE-ANALYSIS 6.3",
    jurisdiction: "CY",
    numbers: [],
    volatility: "VOLATILE",
    trustTier: "commercial",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F5",
    topics: ["formation-package"],
    claim: "The formation package includes issuance of the Certificate of Incorporation and the official company certificates, which are the core documents for opening accounts and signing contracts.",
    sourceType: "refalco-commercial",
    sourceRef: "MB 2.1 / SOURCE-ANALYSIS 6.3",
    jurisdiction: "CY",
    numbers: [],
    volatility: "VOLATILE",
    trustTier: "commercial",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F6",
    topics: ["formation-package"],
    claim: "The formation package includes the Company Secretary for 4 consecutive months. The Company Secretary is a statutory corporate function required of a Cyprus company, not a personal assistant.",
    sourceType: "refalco-commercial",
    sourceRef: "MB 2.1 / SOURCE-ANALYSIS 6.3",
    jurisdiction: "CY",
    numbers: [{ value: "4 months", kind: "duration" }],
    volatility: "VOLATILE",
    trustTier: "commercial",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F7",
    topics: ["formation-package"],
    claim: "The formation package includes the Registered Address for 4 consecutive months. It is the company's official address in Cyprus for correspondence, not a private office or an apartment.",
    sourceType: "refalco-commercial",
    sourceRef: "MB 2.1 / SOURCE-ANALYSIS 6.3",
    jurisdiction: "CY",
    numbers: [{ value: "4 months", kind: "duration" }],
    volatility: "VOLATILE",
    trustTier: "commercial",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F8",
    topics: ["formation-package"],
    claim: "The formation package is managed remotely, so the early procedures are completed without the customer travelling to Cyprus.",
    sourceType: "refalco-commercial",
    sourceRef: "MB 2.1 / SOURCE-ANALYSIS 6.3",
    jurisdiction: "CY",
    numbers: [],
    volatility: "VOLATILE",
    trustTier: "commercial",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F9",
    topics: ["formation-package"],
    claim: "The Cyprus formation package is sold at a single headline price plus VAT, and REFAL states that price only as it is currently published in the live offers table, never from memory and never as an estimate.",
    sourceType: "refalco-commercial",
    sourceRef: "MB 2.1 / SOURCE-ANALYSIS 6.3",
    jurisdiction: "CY",
    numbers: [],
    volatility: "VOLATILE",
    trustTier: "commercial",
    effectiveFrom: null,
    notes: "The figure itself lives in refal_offers_and_pricing (MB-DYN6) and is deliberately absent from this row.",
  },

  // ------------------------------------------------ 6.4 structural guidance
  {
    id: "MB-F10",
    topics: ["company-structures"],
    claim: "When the customer represents a large commercial entity or an existing international company, REFAL does not assume a new Ltd is needed and instead explains Branch and Subsidiary as corporate advisory options.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.1 / SOURCE-ANALYSIS 6.4",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "explanatory",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F11",
    topics: ["shareholder-vs-director"],
    claim: "A shareholder is the owner of the company's shares and capital.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.1 / SOURCE-ANALYSIS 6.4",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "explanatory",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F12",
    topics: ["shareholder-vs-director"],
    claim: "A director is the executive, administrative and legal officer who manages the company.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.1 / SOURCE-ANALYSIS 6.4",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "explanatory",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F13",
    topics: ["shareholder-vs-director"],
    claim: "REFAL puts it simply for the customer: the shareholder is the owner and the director is the person who runs the company, and the same person can be both depending on the structure.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.1 / SOURCE-ANALYSIS 6.4",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "explanatory",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F14",
    topics: ["ownership-changes"],
    claim: "The Cyprus structure is flexible, so partners and directors can be changed later and nothing has to be fixed in stone on day one. REFAL asks early whether an investor or partner is expected, because it is better to know from the start.",
    sourceType: "cy-authority",
    sourceRef: "MB 2.1 / SOURCE-ANALYSIS 6.4",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "Doubles as an opportunity filter, so the question is part of the fact.",
  },
  {
    id: "MB-F15",
    topics: ["registered-vs-physical-office"],
    claim: "The registered address included for 4 months is an administrative requirement, not workspace. A customer who needs desks, meeting rooms, mail handling or real commercial presence is handled as a physical or virtual office requirement.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.1 / SOURCE-ANALYSIS 6.4",
    jurisdiction: "CY",
    numbers: [{ value: "4 months", kind: "duration" }],
    volatility: "VOLATILE",
    trustTier: "explanatory",
    effectiveFrom: null,
    notes: "Override: topic is STABLE, but the 4 month term is a commercial package term that can change.",
  },
  {
    id: "MB-F16",
    topics: ["privacy-vs-concealment"],
    claim: "Legitimate structural privacy is not the same as concealing the Ultimate Beneficial Owner to evade costs or controls, and REFAL states clearly that illegal concealment is not supported.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.1 / SOURCE-ANALYSIS 6.4",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F17",
    topics: ["dormant-and-liquidation"],
    claim: "Going dormant does not exempt a Cyprus company from its reporting and accounting obligations for as long as it remains on the official register.",
    sourceType: "cy-authority",
    sourceRef: "MB 2.1 / SOURCE-ANALYSIS 6.4",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F18",
    topics: ["dormant-and-liquidation"],
    claim: "Closing a Cyprus company follows formal legal liquidation procedures. Simply neglecting the company is not a way of closing it.",
    sourceType: "cy-authority",
    sourceRef: "MB 2.1 / SOURCE-ANALYSIS 6.4",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },

  // ------------------------------ 6.5 tax, accounting and compliance
  {
    id: "MB-F19",
    topics: ["corporate-tax"],
    claim: "Base corporate tax in Cyprus starts at 15% from the year 2026.",
    sourceType: "cy-authority",
    sourceRef: "MB 2.2 / SOURCE-ANALYSIS 6.5",
    jurisdiction: "CY",
    numbers: [
      { value: "15%", kind: "rate" },
      { value: "2026", kind: "year" },
    ],
    volatility: "VOLATILE",
    trustTier: "regulated",
    effectiveFrom: "2026-01-01",
    notes: "Cyprus was historically 12.5%, so the effective date is the whole point of this row: quoting the rate without the year is wrong in both directions.",
  },
  {
    id: "MB-F20",
    topics: ["ip-box"],
    claim: "Cyprus operates an IP Box regime, an approved tax formulation that can bring the effective rate to about 2.5% to 3% on qualifying profits from intellectual property assets and software development.",
    sourceType: "cy-authority",
    sourceRef: "MB 2.2 / SOURCE-ANALYSIS 6.5",
    jurisdiction: "CY",
    numbers: [{ value: "2.5% to 3%", kind: "rate" }],
    volatility: "VOLATILE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F21",
    topics: ["ip-box"],
    claim: "The IP Box regime is not automatic for every company, so eligibility depends on the nature of the product and the intellectual property behind it.",
    sourceType: "cy-authority",
    sourceRef: "MB 2.2 / SOURCE-ANALYSIS 6.5",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "Override: topic is VOLATILE, but this is the eligibility qualifier and stays true whatever the rate does.",
  },
  {
    id: "MB-F22",
    topics: ["dividends-vs-salary"],
    claim: "Distributed profits are taxed differently from personal salary, and whether profits can be drawn as dividends depends on the person's own tax residency and on the applicable Double Tax Treaties.",
    sourceType: "cy-authority",
    sourceRef: "MB 2.2 / SOURCE-ANALYSIS 6.5",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F23",
    topics: ["corporate-tax", "dividends-vs-salary"],
    claim: "REFAL refuses to give a decisive personal tax opinion and converts the question into a tax advisory lead for a specialist instead.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.2 / SOURCE-ANALYSIS 6.5",
    jurisdiction: "GLOBAL",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "Override: the corporate-tax topic is VOLATILE, but this is a refusal rule carrying no figure that can go stale.",
  },
  {
    id: "MB-F24",
    topics: ["holding-vs-trading"],
    claim: "A holding company exists to own shares in other companies, assets, property or intellectual property, while a trading company runs import, export, services or direct sales operations.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.2 / SOURCE-ANALYSIS 6.5",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "explanatory",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F25",
    topics: ["holding-vs-trading"],
    claim: "REFAL separates the two cases by asking a holding customer how many companies or assets they own, in which countries, and whether distributions go to other entities, and by asking a trading customer about the products, the supplier, whether the customers are EU or non EU, and whether there are goods and warehouses.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.2 / SOURCE-ANALYSIS 6.5",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "explanatory",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F26",
    topics: ["holding-vs-trading", "vat-and-eori"],
    claim: "A holding company's compliance work is review of the international ownership structure and confirmation of Substance requirements, while a trading company must obtain a VAT number, register for EORI for customs, and define its shipping and transport procedures.",
    sourceType: "cy-authority",
    sourceRef: "MB 2.2 / SOURCE-ANALYSIS 6.5",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "Override: holding-vs-trading is explanatory, but VAT and EORI registration is a statutory obligation, so the stricter of the two owning topics wins.",
  },
  {
    id: "MB-F27",
    topics: ["holding-vs-trading", "vat-and-eori"],
    claim: "A holding company usually employs only a senior management team, while a trading company needs payroll, social insurance, and work permits for non EU labour.",
    sourceType: "cy-authority",
    sourceRef: "MB 2.2 / SOURCE-ANALYSIS 6.5",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "Override: holding-vs-trading is explanatory, but payroll, social insurance and permits are statutory obligations.",
  },

  // ------------------------------- 6.6 banking and payment gateways
  {
    id: "MB-F28",
    topics: ["banking-and-payment-gateways"],
    claim: "REFAL never gives a definitive promise about opening a bank account or activating a payment gateway such as Stripe, PayPal, Amazon or Shopify. She says honestly that nobody can promise another institution's approval, and pivots to building a clean file from day one.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.3 / SOURCE-ANALYSIS 6.6",
    jurisdiction: "GLOBAL",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "The golden banking rule, and the template for every can you guarantee X answer.",
  },
  {
    id: "MB-F29",
    topics: ["banking-and-payment-gateways"],
    claim: "The final decision on a bank account or a payment gateway belongs to the financial institution's own risk assessment and its KYC and AML compliance requirements.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.3 / SOURCE-ANALYSIS 6.6",
    jurisdiction: "GLOBAL",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },

  // --------------------------- 6.7 permanent residency and Non Dom
  {
    id: "MB-F30",
    topics: ["permanent-residency"],
    claim: "Cyprus permanent residency requires a qualifying investment of at least €300,000 plus VAT where applicable.",
    sourceType: "cy-authority",
    sourceRef: "MB 2.4 / SOURCE-ANALYSIS 6.7",
    jurisdiction: "CY",
    numbers: [{ value: "€300,000 plus VAT", kind: "amount" }],
    volatility: "VOLATILE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F31",
    topics: ["permanent-residency"],
    claim: "The main applicant for Cyprus permanent residency must prove annual income from outside Cyprus of €50,000 per year.",
    sourceType: "cy-authority",
    sourceRef: "MB 2.4 / SOURCE-ANALYSIS 6.7",
    jurisdiction: "CY",
    numbers: [{ value: "€50,000", kind: "amount" }],
    volatility: "VOLATILE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F32",
    topics: ["permanent-residency"],
    claim: "A spouse adds €15,000 per year to the proven annual income requirement for Cyprus permanent residency.",
    sourceType: "cy-authority",
    sourceRef: "MB 2.4 / SOURCE-ANALYSIS 6.7",
    jurisdiction: "CY",
    numbers: [{ value: "€15,000", kind: "amount" }],
    volatility: "VOLATILE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F33",
    topics: ["permanent-residency"],
    claim: "Each eligible minor child adds €10,000 per year to the proven annual income requirement for Cyprus permanent residency.",
    sourceType: "cy-authority",
    sourceRef: "MB 2.4 / SOURCE-ANALYSIS 6.7",
    jurisdiction: "CY",
    numbers: [{ value: "€10,000", kind: "amount" }],
    volatility: "VOLATILE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F34",
    topics: ["non-dom-status"],
    claim: "Non Dom status, for individuals who newly become Cyprus tax residents, brings the rate to 0% on dividends and interest for 17 years.",
    sourceType: "cy-authority",
    sourceRef: "MB 2.4 / SOURCE-ANALYSIS 6.7",
    jurisdiction: "CY",
    numbers: [
      { value: "0%", kind: "rate" },
      { value: "17 years", kind: "duration" },
    ],
    volatility: "VOLATILE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F35",
    topics: ["source-of-funds-vs-wealth"],
    claim: "Source of Funds is the direct path of the money used in this specific transaction, for example a transfer from a named personal bank account or the sale of a specific property.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.4 / SOURCE-ANALYSIS 6.7",
    jurisdiction: "GLOBAL",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F36",
    topics: ["source-of-funds-vs-wealth"],
    claim: "Source of Wealth is the cumulative history of how the customer's wealth was built over the years, such as business profits, inheritance or earlier investments.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.4 / SOURCE-ANALYSIS 6.7",
    jurisdiction: "GLOBAL",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F37",
    topics: ["source-of-funds-vs-wealth"],
    claim: "REFAL explains comfortably and without interrogating the customer that banks and immigration authorities require documentation of the Source of Funds for the deal, and in some cases the general Source of Wealth, as a normal standard compliance step.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.4 / SOURCE-ANALYSIS 6.7",
    jurisdiction: "GLOBAL",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F38",
    topics: ["permanent-residency"],
    claim: "Category A of the Cyprus residency programme is a new residential house or apartment at a minimum of €300,000 plus VAT, preferably a first sale directly from the developer, and it is the most prominent option for customers.",
    sourceType: "cy-authority",
    sourceRef: "MB 2.4 / SOURCE-ANALYSIS 6.7",
    jurisdiction: "CY",
    numbers: [{ value: "€300,000 plus VAT", kind: "amount" }],
    volatility: "VOLATILE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "Category A is the only one of the four that carries the VAT qualifier.",
  },
  {
    id: "MB-F39",
    topics: ["permanent-residency"],
    claim: "Category B of the Cyprus residency programme is other property types such as offices, shops or hotels at a minimum of €300,000, typically combined or redeveloped commercial property.",
    sourceType: "cy-authority",
    sourceRef: "MB 2.4 / SOURCE-ANALYSIS 6.7",
    jurisdiction: "CY",
    numbers: [{ value: "€300,000", kind: "amount" }],
    volatility: "VOLATILE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F40",
    topics: ["permanent-residency"],
    claim: "Category C of the Cyprus residency programme is investment of at least €300,000 in the share capital of a Cyprus company that operates, has employees and has real presence in Cyprus.",
    sourceType: "cy-authority",
    sourceRef: "MB 2.4 / SOURCE-ANALYSIS 6.7",
    jurisdiction: "CY",
    numbers: [{ value: "€300,000", kind: "amount" }],
    volatility: "VOLATILE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F41",
    topics: ["permanent-residency"],
    claim: "Category D of the Cyprus residency programme is at least €300,000 in units of qualifying Cyprus investment funds such as AIF or AIFLNP.",
    sourceType: "cy-authority",
    sourceRef: "MB 2.4 / SOURCE-ANALYSIS 6.7",
    jurisdiction: "CY",
    numbers: [{ value: "€300,000", kind: "amount" }],
    volatility: "VOLATILE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F42",
    topics: ["relocation-checklist"],
    claim: "For a relocating family REFAL distinguishes public, private and international schools with British or English curricula, and asks the children's ages so the right schools and areas can be shortlisted.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.4 / SOURCE-ANALYSIS 6.7",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "explanatory",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F43",
    topics: ["relocation-checklist"],
    claim: "Cyprus has a national health system called GESY, and private health insurance can be added on top of it.",
    sourceType: "cy-authority",
    sourceRef: "MB 2.4 / SOURCE-ANALYSIS 6.7",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "explanatory",
    effectiveFrom: null,
    notes: "GESY is a government programme, so a reviewer verifies it against the authority even though the tier stays explanatory.",
  },
  {
    id: "MB-F44",
    topics: ["relocation-checklist"],
    claim: "Housing, transport and car purchase costs in Cyprus are variable, so REFAL gives no generic numbers and instead requires a fresh current estimate based on the city and the family size.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.4 / SOURCE-ANALYSIS 6.7",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "explanatory",
    effectiveFrom: null,
    notes: "",
  },

  // --------------------------------------------------- 6.8 real estate
  {
    id: "MB-F45",
    topics: ["property-buyer-journey"],
    claim: "The Cyprus property buyer journey runs through search, selection, reservation deposit, legal due diligence, contract, payment plan, tax and VAT, transfer and registration, delivery, then ongoing management.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.5 / SOURCE-ANALYSIS 6.8",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "explanatory",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F46",
    topics: ["offplan-vs-completed"],
    claim: "A completed property suits a buyer who wants a home to move into or a fast rental yield.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.5 / SOURCE-ANALYSIS 6.8",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "explanatory",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F47",
    topics: ["offplan-vs-completed"],
    claim: "An off plan property suits a buyer who needs an easier payment plan and can accept a future delivery date.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.5 / SOURCE-ANALYSIS 6.8",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "explanatory",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F48",
    topics: ["property-vat"],
    claim: "The base VAT rate on new property in Cyprus is 19%, and a reduced rate of 5% exists under special conditions for direct personal use.",
    sourceType: "cy-authority",
    sourceRef: "MB 2.5 / SOURCE-ANALYSIS 6.8",
    jurisdiction: "CY",
    numbers: [
      { value: "19%", kind: "rate" },
      { value: "5%", kind: "rate" },
    ],
    volatility: "VOLATILE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F49",
    topics: ["property-vat"],
    claim: "Property VAT is calculated precisely by the team for the specific case, and REFAL avoids giving loose generic numbers.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.5 / SOURCE-ANALYSIS 6.8",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "Override: topic is VOLATILE, but this is a refusal rule with no rate of its own to expire.",
  },
  {
    id: "MB-F50",
    topics: ["property-buyer-journey"],
    claim: "REFAL is categorically forbidden from guessing or stating a fixed reservation deposit amount. The terms and the value differ per project and per property and are called dynamically from the live property database.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.5 / SOURCE-ANALYSIS 6.8",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "commercial",
    effectiveFrom: null,
    notes: "Override: topic is explanatory, but this rule guards a price figure, so a breach is a mis-quoted commercial term.",
  },
  {
    id: "MB-F51",
    topics: ["cyprus-cities"],
    claim: "Limassol is the international business hub, coastal and luxury, the most expensive city in Cyprus, and it suits capital growth, luxury investment, high net worth investors and international corporate activity.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.5 / SOURCE-ANALYSIS 6.8",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "explanatory",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F52",
    topics: ["cyprus-cities"],
    claim: "Larnaca is a fast growing coastal city close to the airport with medium and rising prices, strong rental yields and major infrastructure development plans, and it suits investors seeking growth opportunities.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.5 / SOURCE-ANALYSIS 6.8",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "explanatory",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F53",
    topics: ["cyprus-cities"],
    claim: "Paphos is a quiet lifestyle and tourism city at medium prices, suiting international buyers, holiday homes, short and long term rentals and family living.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.5 / SOURCE-ANALYSIS 6.8",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "explanatory",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F54",
    topics: ["cyprus-cities"],
    claim: "Nicosia is the capital and the administrative, governmental and university centre, with stable prices built on local demand and very stable long term rentals to students, corporate and institutional staff.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.5 / SOURCE-ANALYSIS 6.8",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "explanatory",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F55",
    topics: ["cyprus-cities"],
    claim: "REFAL refuses to quote a return percentage to please the customer. She explains that the return depends on the project, the price, the expected rent and the costs, asks for the budget and the area so it can be computed on real figures, states plainly that nobody can guarantee a future property price, and redirects to choosing a property with strong fundamentals in an in demand location.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.5 / SOURCE-ANALYSIS 6.8",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "explanatory",
    effectiveFrom: null,
    notes: "",
  },

  // ------------------- 6.9 legal, IP, landowners and construction
  {
    id: "MB-F56",
    topics: ["landowners-and-construction"],
    claim: "Landowner partnership deals and major construction tenders involve assets worth millions, so REFAL performs rapid silent filtering instead of treating them as an ordinary property enquiry.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.6 / SOURCE-ANALYSIS 6.9",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "Worth millions is an order of magnitude in the manual, not a stated figure, so no number entry.",
  },
  {
    id: "MB-F57",
    topics: ["landowners-and-construction"],
    claim: "A landowner joint venture opportunity is signalled when the customer says they own land in Cyprus and want to develop it or partner with a developer.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.6 / SOURCE-ANALYSIS 6.9",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F58",
    topics: ["landowners-and-construction"],
    claim: "On a landowner joint venture REFAL asks for the land location, the area, the building density, and whether preliminary permits already exist.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.6 / SOURCE-ANALYSIS 6.9",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F59",
    topics: ["landowners-and-construction"],
    claim: "Because a land development opportunity is not an ordinary property purchase, REFAL states that the file requires direct review by the development and investment team and escalates it there.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.6 / SOURCE-ANALYSIS 6.9",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F60",
    topics: ["landowners-and-construction"],
    claim: "A construction tender opportunity is signalled when the customer says they need a contractor for a large project or that they have a construction tender.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.6 / SOURCE-ANALYSIS 6.9",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F61",
    topics: ["landowners-and-construction"],
    claim: "On a construction tender REFAL asks for the project size, the location, whether engineering plans such as a BOQ or architectural drawings exist, and the planned start timeline.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.6 / SOURCE-ANALYSIS 6.9",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F62",
    topics: ["landowners-and-construction"],
    claim: "REFAL raises an urgent executive summary of a construction tender to the group's construction sector and gives no prices and no preliminary estimates of her own at all.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.6 / SOURCE-ANALYSIS 6.9",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F63",
    topics: ["legal-ip-contracts"],
    claim: "Refalco registers trademarks in Cyprus and across the European Union.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.6 / SOURCE-ANALYSIS 6.9",
    jurisdiction: "EU",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F64",
    topics: ["legal-ip-contracts"],
    claim: "Refalco drafts Shareholders Agreements, the governance agreements between owners and partners that prevent future disputes.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.6 / SOURCE-ANALYSIS 6.9",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F65",
    topics: ["legal-ip-contracts"],
    claim: "Refalco drafts service and employment agreements, covering service provision, development work and employee contracts.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.6 / SOURCE-ANALYSIS 6.9",
    jurisdiction: "CY",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-F66",
    topics: ["legal-ip-contracts"],
    claim: "Refalco advises on website terms and conditions and on European data protection compliance under GDPR.",
    sourceType: "mb-manual",
    sourceRef: "MB 2.6 / SOURCE-ANALYSIS 6.9",
    jurisdiction: "EU",
    numbers: [],
    volatility: "STABLE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "",
  },

  // ------------------------------------------ 6.1 Refalco credibility
  {
    id: "MB-C1",
    topics: ["company-profile"],
    claim: "Refalco has operational roots in Cyprus going back to the year 2000.",
    sourceType: "refalco-commercial",
    sourceRef: "MB 2.0, 3.0 / SOURCE-ANALYSIS 6.1",
    jurisdiction: "CY",
    numbers: [{ value: "2000", kind: "year" }],
    volatility: "VOLATILE",
    trustTier: "commercial",
    effectiveFrom: null,
    notes: "",
  },
  {
    id: "MB-C2",
    topics: ["company-profile"],
    claim: "Refalco has more than 20 years of field experience.",
    sourceType: "refalco-commercial",
    sourceRef: "MB 2.0, 3.0 / SOURCE-ANALYSIS 6.1",
    jurisdiction: "CY",
    numbers: [{ value: "20 years", kind: "duration" }],
    volatility: "VOLATILE",
    trustTier: "commercial",
    effectiveFrom: null,
    notes: "An elapsed time claim drifts on its own, so it is VOLATILE even though the founding year is fixed.",
  },
  {
    id: "MB-C3",
    topics: ["company-profile"],
    claim: "Refalco has delivered 47 real estate development projects.",
    sourceType: "refalco-commercial",
    sourceRef: "MB 2.0, 3.0 / SOURCE-ANALYSIS 6.1",
    jurisdiction: "CY",
    numbers: [{ value: "47", kind: "count" }],
    volatility: "VOLATILE",
    trustTier: "commercial",
    effectiveFrom: null,
    notes: "A project count goes stale as soon as the next project completes.",
  },
  {
    id: "MB-C4",
    topics: ["company-profile"],
    claim: "Refalco has delivered more than 400 multi sector projects.",
    sourceType: "refalco-commercial",
    sourceRef: "MB 2.0, 3.0 / SOURCE-ANALYSIS 6.1",
    jurisdiction: "CY",
    numbers: [{ value: "400", kind: "count" }],
    volatility: "VOLATILE",
    trustTier: "commercial",
    effectiveFrom: null,
    notes: "A project count goes stale as soon as the next project completes.",
  },
  {
    id: "MB-C5",
    topics: ["company-profile"],
    claim: "Refalco is not a narrow company registration office. It positions itself as a gateway to comprehensive investment and structural solutions.",
    sourceType: "refalco-commercial",
    sourceRef: "MB 2.0, 3.0 / SOURCE-ANALYSIS 6.1",
    jurisdiction: "CY",
    numbers: [],
    volatility: "VOLATILE",
    trustTier: "commercial",
    effectiveFrom: null,
    notes: "",
  },

  // ------------------------------------- 7.4 jurisdiction benchmarking
  {
    id: "MB-J0",
    topics: ["jurisdiction-dubai", "jurisdiction-estonia", "jurisdiction-malta-bulgaria", "jurisdiction-usa"],
    claim: "REFAL never attacks another country and never claims Cyprus is always the best. She compares consultatively and analytically, highlighting Cyprus's structural differences: EU market access, real Substance, and the fusion of investment with residency.",
    sourceType: "mb-manual",
    sourceRef: "MB 3.3 / SOURCE-ANALYSIS 7.4",
    jurisdiction: "GLOBAL",
    numbers: [],
    volatility: "STABLE",
    trustTier: "explanatory",
    effectiveFrom: null,
    notes: "The posture rule that every jurisdiction comparison is bound by.",
  },
  {
    id: "MB-J1",
    topics: ["jurisdiction-dubai"],
    claim: "Dubai is an excellent environment with no personal income tax, and a Cyprus company is not necessarily a replacement for it. Cyprus adds a direct EU gateway, a European VAT number, and real presence that eases payment gateways and European expansion.",
    sourceType: "foreign-authority",
    sourceRef: "MB 3.3 / SOURCE-ANALYSIS 7.4",
    jurisdiction: "AE",
    numbers: [],
    volatility: "VOLATILE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "Override: topic is STABLE and explanatory, but this asserts another country's tax position, which a reviewer must re-verify against that authority.",
  },
  {
    id: "MB-J2",
    topics: ["jurisdiction-estonia"],
    claim: "Estonia is excellent for e Residency and digital solutions but grants no actual residence or property stability and taxes profits at distribution. Cyprus provides a real environment fusing business with residency and property, plus a strong IP Box.",
    sourceType: "foreign-authority",
    sourceRef: "MB 3.3 / SOURCE-ANALYSIS 7.4",
    jurisdiction: "EE",
    numbers: [],
    volatility: "VOLATILE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "Override: topic is STABLE and explanatory, but taxation at distribution is a foreign tax treatment that needs re-verification.",
  },
  {
    id: "MB-J3",
    topics: ["jurisdiction-malta-bulgaria"],
    claim: "Bulgaria offers 10% tax but has banking constraints and language and environmental complexity, and Malta runs a complex refund system. Cyprus offers a direct system at 15%, prevalent English, a property market and stable residency.",
    sourceType: "foreign-authority",
    sourceRef: "MB 3.3 / SOURCE-ANALYSIS 7.4",
    jurisdiction: "EU",
    numbers: [
      { value: "10%", kind: "rate" },
      { value: "15%", kind: "rate" },
    ],
    volatility: "VOLATILE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "Override: topic is STABLE and explanatory, but this row carries two live tax rates. The 15% is the same figure as MB-F19 and must be kept in step with it.",
  },
  {
    id: "MB-J4",
    topics: ["jurisdiction-usa"],
    claim: "A US LLC or Inc is excellent for e commerce and Stripe sales but brings tax complexity for non residents and gives no direct EU market access.",
    sourceType: "foreign-authority",
    sourceRef: "MB 3.3 / SOURCE-ANALYSIS 7.4",
    jurisdiction: "US",
    numbers: [],
    volatility: "STABLE",
    trustTier: "explanatory",
    effectiveFrom: null,
    notes: "Kept at the topic's values: it asserts relative complexity, not a specific rate or rule that can expire.",
  },

  // ----------------------------------- 9.4 the six never-freeze variables
  {
    id: "MB-DYN1",
    topics: [],
    claim: "Available properties, unit prices, technical details and current availability are read live from the property database for the specific request and are never stated from memory.",
    sourceType: "refalco-commercial",
    sourceRef: "MB 5.3 / SOURCE-ANALYSIS 9.4",
    jurisdiction: "CY",
    numbers: [],
    volatility: "VOLATILE",
    trustTier: "commercial",
    effectiveFrom: null,
    notes: "No owning topic, so volatility and tier are set here: it governs live commercial inventory.",
  },
  {
    id: "MB-DYN2",
    topics: [],
    claim: "The reservation deposit amount and conditions are read live from the property database for the specific project and are never stated from memory.",
    sourceType: "refalco-commercial",
    sourceRef: "MB 5.3 / SOURCE-ANALYSIS 9.4",
    jurisdiction: "CY",
    numbers: [],
    volatility: "VOLATILE",
    trustTier: "commercial",
    effectiveFrom: null,
    notes: "No owning topic. Pairs with MB-F50, which is the customer facing form of the same prohibition.",
  },
  {
    id: "MB-DYN3",
    topics: [],
    claim: "Annual renewal costs for secretary, registered address, accounting, audit and taxes are read live from the corporate pricing source when the customer asks about annual costs, and are never stated from memory.",
    sourceType: "refalco-commercial",
    sourceRef: "MB 5.3 / SOURCE-ANALYSIS 9.4",
    jurisdiction: "CY",
    numbers: [],
    volatility: "VOLATILE",
    trustTier: "commercial",
    effectiveFrom: null,
    notes: "No owning topic, so volatility and tier are set here: it governs a published price list.",
  },
  {
    id: "MB-DYN4",
    topics: [],
    claim: "Available appointment slots and consultant schedules by timezone are read live from the calendar integration when moving to booking, and are never stated from memory.",
    sourceType: "mb-manual",
    sourceRef: "MB 5.3 / SOURCE-ANALYSIS 9.4",
    jurisdiction: "GLOBAL",
    numbers: [],
    volatility: "VOLATILE",
    trustTier: "explanatory",
    effectiveFrom: null,
    notes: "No owning topic. An operational scheduling rule with no commercial or legal figure behind it.",
  },
  {
    id: "MB-DYN5",
    topics: [],
    claim: "Government fees, land registry fees and residency application fees are read live from the regulatory rates source when a total deal cost is computed, and are never stated from memory.",
    sourceType: "cy-authority",
    sourceRef: "MB 5.3 / SOURCE-ANALYSIS 9.4",
    jurisdiction: "CY",
    numbers: [],
    volatility: "VOLATILE",
    trustTier: "regulated",
    effectiveFrom: null,
    notes: "No owning topic. These are authority set fees, so the tier is regulated.",
  },
  {
    id: "MB-DYN6",
    topics: [],
    claim: "Current promotional offers, period discounts and included extras are read live from the offers and pricing table to confirm which offer is actually in force, and are never stated from memory.",
    sourceType: "refalco-commercial",
    sourceRef: "MB 5.3 / SOURCE-ANALYSIS 9.4",
    jurisdiction: "CY",
    numbers: [],
    volatility: "VOLATILE",
    trustTier: "commercial",
    effectiveFrom: null,
    notes: "No owning topic. This is the rule that keeps the formation package price out of MB-F9 and out of every corpus chunk.",
  },
];

module.exports = { ROWS };
