-- MIG-01 seed / P3.9 W3.9.4 — GENERATED FILE, DO NOT EDIT BY HAND.
-- Regenerate with: node scripts/generateFactRegisterSeed.js
-- Source of truth: src/factCatalogue.js + the seeding rules in src/factRegister.js.
--
-- Rule 1, BOSS's authority instruction: MB manual facts are seeded APPROVED,
-- reviewer BOSS, verified 2026-10-07. They are live from day one and are
-- NOT blocked waiting for an external reviewer.
--
-- Rule 2 is what makes that safe: every row carries expiry_or_review_at, so a
-- figure that goes stale stops being asserted on its own, with no code change
-- and no redeploy. The 20 high risk facts named in W3.9.2 are capped at a
-- 90 day cadence, enforced by a check constraint as well as by this seed.
--
-- 82 rows. 20 high risk. 21 carry at least one number.
--
-- Run AFTER 20261009180000_refal_fact_register.sql. Safe to run twice: an
-- existing row is refreshed to the catalogue's claim and provenance, but its
-- status, reviewer, verified_at and review date are LEFT ALONE, so re-running
-- this file can never silently un-expire a fact a reviewer retired or revive
-- one they blocked.

insert into public.refal_fact_register (
  fact_id, claim_text, topics, source_type, source_url_or_document, source_ref, jurisdiction, numbers, volatility, trust_tier, high_risk, reviewer, verified_at, effective_from, expiry_or_review_at, review_cadence_days, approved_languages, status, notes
) values
  ('MB-F1', 'A Cyprus company moves through ten stages: idea, incorporation, banking, tax, accounting, operations, growth, changes, renewal, closure.', array['company-lifecycle']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.1 / SOURCE-ANALYSIS 6.2', 'CY', '[]'::jsonb, 'STABLE', 'explanatory', false, 'BOSS', '2026-10-07'::date, null, '2027-10-07'::date, 365, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F1
  ('MB-F2', 'The Refalco formation package includes incorporation of a Cyprus Ltd through the full official procedures, usually completed in about two weeks once the customer''s documents are complete.', array['formation-package']::text[], 'refalco-commercial', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.1 / SOURCE-ANALYSIS 6.3', 'CY', '[{"value":"about two weeks","kind":"duration"}]'::jsonb, 'VOLATILE', 'commercial', true, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F2 [high risk]
  ('MB-F3', 'The formation package includes reserving the company name and obtaining its approval from the Cyprus Registrar of Companies, which is the step that formally starts the commercial identity.', array['formation-package']::text[], 'refalco-commercial', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.1 / SOURCE-ANALYSIS 6.3', 'CY', '[]'::jsonb, 'VOLATILE', 'commercial', false, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F3
  ('MB-F4', 'The formation package includes preparing and attesting the incorporation documents, drafting the Memorandum and Articles of Association and filing them so the file is not rejected administratively.', array['formation-package']::text[], 'refalco-commercial', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.1 / SOURCE-ANALYSIS 6.3', 'CY', '[]'::jsonb, 'VOLATILE', 'commercial', false, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F4
  ('MB-F5', 'The formation package includes issuance of the Certificate of Incorporation and the official company certificates, which are the core documents for opening accounts and signing contracts.', array['formation-package']::text[], 'refalco-commercial', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.1 / SOURCE-ANALYSIS 6.3', 'CY', '[]'::jsonb, 'VOLATILE', 'commercial', false, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F5
  ('MB-F6', 'The formation package includes the Company Secretary for 4 consecutive months. The Company Secretary is a statutory corporate function required of a Cyprus company, not a personal assistant.', array['formation-package']::text[], 'refalco-commercial', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.1 / SOURCE-ANALYSIS 6.3', 'CY', '[{"value":"4 months","kind":"duration"}]'::jsonb, 'VOLATILE', 'commercial', true, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F6 [high risk]
  ('MB-F7', 'The formation package includes the Registered Address for 4 consecutive months. It is the company''s official address in Cyprus for correspondence, not a private office or an apartment.', array['formation-package']::text[], 'refalco-commercial', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.1 / SOURCE-ANALYSIS 6.3', 'CY', '[{"value":"4 months","kind":"duration"}]'::jsonb, 'VOLATILE', 'commercial', true, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F7 [high risk]
  ('MB-F8', 'The formation package is managed remotely, so the early procedures are completed without the customer travelling to Cyprus.', array['formation-package']::text[], 'refalco-commercial', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.1 / SOURCE-ANALYSIS 6.3', 'CY', '[]'::jsonb, 'VOLATILE', 'commercial', false, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F8
  ('MB-F9', 'The Cyprus formation package is sold at a single headline price plus VAT, and REFAL states that price only as it is currently published in the live offers table, never from memory and never as an estimate.', array['formation-package']::text[], 'refalco-commercial', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.1 / SOURCE-ANALYSIS 6.3', 'CY', '[]'::jsonb, 'VOLATILE', 'commercial', true, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', 'The figure itself lives in refal_offers_and_pricing (MB-DYN6) and is deliberately absent from this row.'),   -- MB-F9 [high risk]
  ('MB-F10', 'When the customer represents a large commercial entity or an existing international company, REFAL does not assume a new Ltd is needed and instead explains Branch and Subsidiary as corporate advisory options.', array['company-structures']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.1 / SOURCE-ANALYSIS 6.4', 'CY', '[]'::jsonb, 'STABLE', 'explanatory', false, 'BOSS', '2026-10-07'::date, null, '2027-10-07'::date, 365, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F10
  ('MB-F11', 'A shareholder is the owner of the company''s shares and capital.', array['shareholder-vs-director']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.1 / SOURCE-ANALYSIS 6.4', 'CY', '[]'::jsonb, 'STABLE', 'explanatory', false, 'BOSS', '2026-10-07'::date, null, '2027-10-07'::date, 365, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F11
  ('MB-F12', 'A director is the executive, administrative and legal officer who manages the company.', array['shareholder-vs-director']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.1 / SOURCE-ANALYSIS 6.4', 'CY', '[]'::jsonb, 'STABLE', 'explanatory', false, 'BOSS', '2026-10-07'::date, null, '2027-10-07'::date, 365, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F12
  ('MB-F13', 'REFAL puts it simply for the customer: the shareholder is the owner and the director is the person who runs the company, and the same person can be both depending on the structure.', array['shareholder-vs-director']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.1 / SOURCE-ANALYSIS 6.4', 'CY', '[]'::jsonb, 'STABLE', 'explanatory', false, 'BOSS', '2026-10-07'::date, null, '2027-10-07'::date, 365, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F13
  ('MB-F14', 'The Cyprus structure is flexible, so partners and directors can be changed later and nothing has to be fixed in stone on day one. REFAL asks early whether an investor or partner is expected, because it is better to know from the start.', array['ownership-changes']::text[], 'cy-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.1 / SOURCE-ANALYSIS 6.4', 'CY', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', 'Doubles as an opportunity filter, so the question is part of the fact.'),   -- MB-F14
  ('MB-F15', 'The registered address included for 4 months is an administrative requirement, not workspace. A customer who needs desks, meeting rooms, mail handling or real commercial presence is handled as a physical or virtual office requirement.', array['registered-vs-physical-office']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.1 / SOURCE-ANALYSIS 6.4', 'CY', '[{"value":"4 months","kind":"duration"}]'::jsonb, 'VOLATILE', 'explanatory', false, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', 'Override: topic is STABLE, but the 4 month term is a commercial package term that can change.'),   -- MB-F15
  ('MB-F16', 'Legitimate structural privacy is not the same as concealing the Ultimate Beneficial Owner to evade costs or controls, and REFAL states clearly that illegal concealment is not supported.', array['privacy-vs-concealment']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.1 / SOURCE-ANALYSIS 6.4', 'CY', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F16
  ('MB-F17', 'Going dormant does not exempt a Cyprus company from its reporting and accounting obligations for as long as it remains on the official register.', array['dormant-and-liquidation']::text[], 'cy-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.1 / SOURCE-ANALYSIS 6.4', 'CY', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F17
  ('MB-F18', 'Closing a Cyprus company follows formal legal liquidation procedures. Simply neglecting the company is not a way of closing it.', array['dormant-and-liquidation']::text[], 'cy-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.1 / SOURCE-ANALYSIS 6.4', 'CY', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F18
  ('MB-F19', 'Base corporate tax in Cyprus starts at 15% from the year 2026.', array['corporate-tax']::text[], 'cy-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.2 / SOURCE-ANALYSIS 6.5', 'CY', '[{"value":"15%","kind":"rate"},{"value":"2026","kind":"year"}]'::jsonb, 'VOLATILE', 'regulated', true, 'BOSS', '2026-10-07'::date, '2026-01-01'::date, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', 'Cyprus was historically 12.5%, so the effective date is the whole point of this row: quoting the rate without the year is wrong in both directions.'),   -- MB-F19 [high risk]
  ('MB-F20', 'Cyprus operates an IP Box regime, an approved tax formulation that can bring the effective rate to about 2.5% to 3% on qualifying profits from intellectual property assets and software development.', array['ip-box']::text[], 'cy-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.2 / SOURCE-ANALYSIS 6.5', 'CY', '[{"value":"2.5% to 3%","kind":"rate"}]'::jsonb, 'VOLATILE', 'regulated', true, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F20 [high risk]
  ('MB-F21', 'The IP Box regime is not automatic for every company, so eligibility depends on the nature of the product and the intellectual property behind it.', array['ip-box']::text[], 'cy-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.2 / SOURCE-ANALYSIS 6.5', 'CY', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', 'Override: topic is VOLATILE, but this is the eligibility qualifier and stays true whatever the rate does.'),   -- MB-F21
  ('MB-F22', 'Distributed profits are taxed differently from personal salary, and whether profits can be drawn as dividends depends on the person''s own tax residency and on the applicable Double Tax Treaties.', array['dividends-vs-salary']::text[], 'cy-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.2 / SOURCE-ANALYSIS 6.5', 'CY', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F22
  ('MB-F23', 'REFAL refuses to give a decisive personal tax opinion and converts the question into a tax advisory lead for a specialist instead.', array['corporate-tax', 'dividends-vs-salary']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.2 / SOURCE-ANALYSIS 6.5', 'GLOBAL', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', 'Override: the corporate-tax topic is VOLATILE, but this is a refusal rule carrying no figure that can go stale.'),   -- MB-F23
  ('MB-F24', 'A holding company exists to own shares in other companies, assets, property or intellectual property, while a trading company runs import, export, services or direct sales operations.', array['holding-vs-trading']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.2 / SOURCE-ANALYSIS 6.5', 'CY', '[]'::jsonb, 'STABLE', 'explanatory', false, 'BOSS', '2026-10-07'::date, null, '2027-10-07'::date, 365, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F24
  ('MB-F25', 'REFAL separates the two cases by asking a holding customer how many companies or assets they own, in which countries, and whether distributions go to other entities, and by asking a trading customer about the products, the supplier, whether the customers are EU or non EU, and whether there are goods and warehouses.', array['holding-vs-trading']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.2 / SOURCE-ANALYSIS 6.5', 'CY', '[]'::jsonb, 'STABLE', 'explanatory', false, 'BOSS', '2026-10-07'::date, null, '2027-10-07'::date, 365, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F25
  ('MB-F26', 'A holding company''s compliance work is review of the international ownership structure and confirmation of Substance requirements, while a trading company must obtain a VAT number, register for EORI for customs, and define its shipping and transport procedures.', array['holding-vs-trading', 'vat-and-eori']::text[], 'cy-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.2 / SOURCE-ANALYSIS 6.5', 'CY', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', 'Override: holding-vs-trading is explanatory, but VAT and EORI registration is a statutory obligation, so the stricter of the two owning topics wins.'),   -- MB-F26
  ('MB-F27', 'A holding company usually employs only a senior management team, while a trading company needs payroll, social insurance, and work permits for non EU labour.', array['holding-vs-trading', 'vat-and-eori']::text[], 'cy-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.2 / SOURCE-ANALYSIS 6.5', 'CY', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', 'Override: holding-vs-trading is explanatory, but payroll, social insurance and permits are statutory obligations.'),   -- MB-F27
  ('MB-F28', 'REFAL never gives a definitive promise about opening a bank account or activating a payment gateway such as Stripe, PayPal, Amazon or Shopify. She says honestly that nobody can promise another institution''s approval, and pivots to building a clean file from day one.', array['banking-and-payment-gateways']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.3 / SOURCE-ANALYSIS 6.6', 'GLOBAL', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', 'The golden banking rule, and the template for every can you guarantee X answer.'),   -- MB-F28
  ('MB-F29', 'The final decision on a bank account or a payment gateway belongs to the financial institution''s own risk assessment and its KYC and AML compliance requirements.', array['banking-and-payment-gateways']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.3 / SOURCE-ANALYSIS 6.6', 'GLOBAL', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F29
  ('MB-F30', 'Cyprus permanent residency requires a qualifying investment of at least €300,000 plus VAT where applicable.', array['permanent-residency']::text[], 'cy-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.4 / SOURCE-ANALYSIS 6.7', 'CY', '[{"value":"€300,000 plus VAT","kind":"amount"}]'::jsonb, 'VOLATILE', 'regulated', true, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F30 [high risk]
  ('MB-F31', 'The main applicant for Cyprus permanent residency must prove annual income from outside Cyprus of €50,000 per year.', array['permanent-residency']::text[], 'cy-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.4 / SOURCE-ANALYSIS 6.7', 'CY', '[{"value":"€50,000","kind":"amount"}]'::jsonb, 'VOLATILE', 'regulated', true, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F31 [high risk]
  ('MB-F32', 'A spouse adds €15,000 per year to the proven annual income requirement for Cyprus permanent residency.', array['permanent-residency']::text[], 'cy-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.4 / SOURCE-ANALYSIS 6.7', 'CY', '[{"value":"€15,000","kind":"amount"}]'::jsonb, 'VOLATILE', 'regulated', true, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F32 [high risk]
  ('MB-F33', 'Each eligible minor child adds €10,000 per year to the proven annual income requirement for Cyprus permanent residency.', array['permanent-residency']::text[], 'cy-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.4 / SOURCE-ANALYSIS 6.7', 'CY', '[{"value":"€10,000","kind":"amount"}]'::jsonb, 'VOLATILE', 'regulated', true, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F33 [high risk]
  ('MB-F34', 'Non Dom status, for individuals who newly become Cyprus tax residents, brings the rate to 0% on dividends and interest for 17 years.', array['non-dom-status']::text[], 'cy-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.4 / SOURCE-ANALYSIS 6.7', 'CY', '[{"value":"0%","kind":"rate"},{"value":"17 years","kind":"duration"}]'::jsonb, 'VOLATILE', 'regulated', true, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F34 [high risk]
  ('MB-F35', 'Source of Funds is the direct path of the money used in this specific transaction, for example a transfer from a named personal bank account or the sale of a specific property.', array['source-of-funds-vs-wealth']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.4 / SOURCE-ANALYSIS 6.7', 'GLOBAL', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F35
  ('MB-F36', 'Source of Wealth is the cumulative history of how the customer''s wealth was built over the years, such as business profits, inheritance or earlier investments.', array['source-of-funds-vs-wealth']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.4 / SOURCE-ANALYSIS 6.7', 'GLOBAL', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F36
  ('MB-F37', 'REFAL explains comfortably and without interrogating the customer that banks and immigration authorities require documentation of the Source of Funds for the deal, and in some cases the general Source of Wealth, as a normal standard compliance step.', array['source-of-funds-vs-wealth']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.4 / SOURCE-ANALYSIS 6.7', 'GLOBAL', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F37
  ('MB-F38', 'Category A of the Cyprus residency programme is a new residential house or apartment at a minimum of €300,000 plus VAT, preferably a first sale directly from the developer, and it is the most prominent option for customers.', array['permanent-residency']::text[], 'cy-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.4 / SOURCE-ANALYSIS 6.7', 'CY', '[{"value":"€300,000 plus VAT","kind":"amount"}]'::jsonb, 'VOLATILE', 'regulated', true, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', 'Category A is the only one of the four that carries the VAT qualifier.'),   -- MB-F38 [high risk]
  ('MB-F39', 'Category B of the Cyprus residency programme is other property types such as offices, shops or hotels at a minimum of €300,000, typically combined or redeveloped commercial property.', array['permanent-residency']::text[], 'cy-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.4 / SOURCE-ANALYSIS 6.7', 'CY', '[{"value":"€300,000","kind":"amount"}]'::jsonb, 'VOLATILE', 'regulated', true, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F39 [high risk]
  ('MB-F40', 'Category C of the Cyprus residency programme is investment of at least €300,000 in the share capital of a Cyprus company that operates, has employees and has real presence in Cyprus.', array['permanent-residency']::text[], 'cy-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.4 / SOURCE-ANALYSIS 6.7', 'CY', '[{"value":"€300,000","kind":"amount"}]'::jsonb, 'VOLATILE', 'regulated', true, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F40 [high risk]
  ('MB-F41', 'Category D of the Cyprus residency programme is at least €300,000 in units of qualifying Cyprus investment funds such as AIF or AIFLNP.', array['permanent-residency']::text[], 'cy-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.4 / SOURCE-ANALYSIS 6.7', 'CY', '[{"value":"€300,000","kind":"amount"}]'::jsonb, 'VOLATILE', 'regulated', true, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F41 [high risk]
  ('MB-F42', 'For a relocating family REFAL distinguishes public, private and international schools with British or English curricula, and asks the children''s ages so the right schools and areas can be shortlisted.', array['relocation-checklist']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.4 / SOURCE-ANALYSIS 6.7', 'CY', '[]'::jsonb, 'STABLE', 'explanatory', false, 'BOSS', '2026-10-07'::date, null, '2027-10-07'::date, 365, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F42
  ('MB-F43', 'Cyprus has a national health system called GESY, and private health insurance can be added on top of it.', array['relocation-checklist']::text[], 'cy-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.4 / SOURCE-ANALYSIS 6.7', 'CY', '[]'::jsonb, 'STABLE', 'explanatory', false, 'BOSS', '2026-10-07'::date, null, '2027-10-07'::date, 365, array['ar', 'en', 'el']::text[], 'approved', 'GESY is a government programme, so a reviewer verifies it against the authority even though the tier stays explanatory.'),   -- MB-F43
  ('MB-F44', 'Housing, transport and car purchase costs in Cyprus are variable, so REFAL gives no generic numbers and instead requires a fresh current estimate based on the city and the family size.', array['relocation-checklist']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.4 / SOURCE-ANALYSIS 6.7', 'CY', '[]'::jsonb, 'STABLE', 'explanatory', false, 'BOSS', '2026-10-07'::date, null, '2027-10-07'::date, 365, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F44
  ('MB-F45', 'The Cyprus property buyer journey runs through search, selection, reservation deposit, legal due diligence, contract, payment plan, tax and VAT, transfer and registration, delivery, then ongoing management.', array['property-buyer-journey']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.5 / SOURCE-ANALYSIS 6.8', 'CY', '[]'::jsonb, 'STABLE', 'explanatory', false, 'BOSS', '2026-10-07'::date, null, '2027-10-07'::date, 365, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F45
  ('MB-F46', 'A completed property suits a buyer who wants a home to move into or a fast rental yield.', array['offplan-vs-completed']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.5 / SOURCE-ANALYSIS 6.8', 'CY', '[]'::jsonb, 'STABLE', 'explanatory', false, 'BOSS', '2026-10-07'::date, null, '2027-10-07'::date, 365, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F46
  ('MB-F47', 'An off plan property suits a buyer who needs an easier payment plan and can accept a future delivery date.', array['offplan-vs-completed']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.5 / SOURCE-ANALYSIS 6.8', 'CY', '[]'::jsonb, 'STABLE', 'explanatory', false, 'BOSS', '2026-10-07'::date, null, '2027-10-07'::date, 365, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F47
  ('MB-F48', 'The base VAT rate on new property in Cyprus is 19%, and a reduced rate of 5% exists under special conditions for direct personal use.', array['property-vat']::text[], 'cy-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.5 / SOURCE-ANALYSIS 6.8', 'CY', '[{"value":"19%","kind":"rate"},{"value":"5%","kind":"rate"}]'::jsonb, 'VOLATILE', 'regulated', true, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F48 [high risk]
  ('MB-F49', 'Property VAT is calculated precisely by the team for the specific case, and REFAL avoids giving loose generic numbers.', array['property-vat']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.5 / SOURCE-ANALYSIS 6.8', 'CY', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', 'Override: topic is VOLATILE, but this is a refusal rule with no rate of its own to expire.'),   -- MB-F49
  ('MB-F50', 'REFAL is categorically forbidden from guessing or stating a fixed reservation deposit amount. The terms and the value differ per project and per property and are called dynamically from the live property database.', array['property-buyer-journey']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.5 / SOURCE-ANALYSIS 6.8', 'CY', '[]'::jsonb, 'STABLE', 'commercial', false, 'BOSS', '2026-10-07'::date, null, '2027-10-07'::date, 365, array['ar', 'en', 'el']::text[], 'approved', 'Override: topic is explanatory, but this rule guards a price figure, so a breach is a mis-quoted commercial term.'),   -- MB-F50
  ('MB-F51', 'Limassol is the international business hub, coastal and luxury, the most expensive city in Cyprus, and it suits capital growth, luxury investment, high net worth investors and international corporate activity.', array['cyprus-cities']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.5 / SOURCE-ANALYSIS 6.8', 'CY', '[]'::jsonb, 'STABLE', 'explanatory', false, 'BOSS', '2026-10-07'::date, null, '2027-10-07'::date, 365, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F51
  ('MB-F52', 'Larnaca is a fast growing coastal city close to the airport with medium and rising prices, strong rental yields and major infrastructure development plans, and it suits investors seeking growth opportunities.', array['cyprus-cities']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.5 / SOURCE-ANALYSIS 6.8', 'CY', '[]'::jsonb, 'STABLE', 'explanatory', false, 'BOSS', '2026-10-07'::date, null, '2027-10-07'::date, 365, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F52
  ('MB-F53', 'Paphos is a quiet lifestyle and tourism city at medium prices, suiting international buyers, holiday homes, short and long term rentals and family living.', array['cyprus-cities']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.5 / SOURCE-ANALYSIS 6.8', 'CY', '[]'::jsonb, 'STABLE', 'explanatory', false, 'BOSS', '2026-10-07'::date, null, '2027-10-07'::date, 365, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F53
  ('MB-F54', 'Nicosia is the capital and the administrative, governmental and university centre, with stable prices built on local demand and very stable long term rentals to students, corporate and institutional staff.', array['cyprus-cities']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.5 / SOURCE-ANALYSIS 6.8', 'CY', '[]'::jsonb, 'STABLE', 'explanatory', false, 'BOSS', '2026-10-07'::date, null, '2027-10-07'::date, 365, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F54
  ('MB-F55', 'REFAL refuses to quote a return percentage to please the customer. She explains that the return depends on the project, the price, the expected rent and the costs, asks for the budget and the area so it can be computed on real figures, states plainly that nobody can guarantee a future property price, and redirects to choosing a property with strong fundamentals in an in demand location.', array['cyprus-cities']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.5 / SOURCE-ANALYSIS 6.8', 'CY', '[]'::jsonb, 'STABLE', 'explanatory', false, 'BOSS', '2026-10-07'::date, null, '2027-10-07'::date, 365, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F55
  ('MB-F56', 'Landowner partnership deals and major construction tenders involve assets worth millions, so REFAL performs rapid silent filtering instead of treating them as an ordinary property enquiry.', array['landowners-and-construction']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.6 / SOURCE-ANALYSIS 6.9', 'CY', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', 'Worth millions is an order of magnitude in the manual, not a stated figure, so no number entry.'),   -- MB-F56
  ('MB-F57', 'A landowner joint venture opportunity is signalled when the customer says they own land in Cyprus and want to develop it or partner with a developer.', array['landowners-and-construction']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.6 / SOURCE-ANALYSIS 6.9', 'CY', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F57
  ('MB-F58', 'On a landowner joint venture REFAL asks for the land location, the area, the building density, and whether preliminary permits already exist.', array['landowners-and-construction']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.6 / SOURCE-ANALYSIS 6.9', 'CY', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F58
  ('MB-F59', 'Because a land development opportunity is not an ordinary property purchase, REFAL states that the file requires direct review by the development and investment team and escalates it there.', array['landowners-and-construction']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.6 / SOURCE-ANALYSIS 6.9', 'CY', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F59
  ('MB-F60', 'A construction tender opportunity is signalled when the customer says they need a contractor for a large project or that they have a construction tender.', array['landowners-and-construction']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.6 / SOURCE-ANALYSIS 6.9', 'CY', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F60
  ('MB-F61', 'On a construction tender REFAL asks for the project size, the location, whether engineering plans such as a BOQ or architectural drawings exist, and the planned start timeline.', array['landowners-and-construction']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.6 / SOURCE-ANALYSIS 6.9', 'CY', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F61
  ('MB-F62', 'REFAL raises an urgent executive summary of a construction tender to the group''s construction sector and gives no prices and no preliminary estimates of her own at all.', array['landowners-and-construction']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.6 / SOURCE-ANALYSIS 6.9', 'CY', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F62
  ('MB-F63', 'Refalco registers trademarks in Cyprus and across the European Union.', array['legal-ip-contracts']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.6 / SOURCE-ANALYSIS 6.9', 'EU', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F63
  ('MB-F64', 'Refalco drafts Shareholders Agreements, the governance agreements between owners and partners that prevent future disputes.', array['legal-ip-contracts']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.6 / SOURCE-ANALYSIS 6.9', 'CY', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F64
  ('MB-F65', 'Refalco drafts service and employment agreements, covering service provision, development work and employee contracts.', array['legal-ip-contracts']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.6 / SOURCE-ANALYSIS 6.9', 'CY', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F65
  ('MB-F66', 'Refalco advises on website terms and conditions and on European data protection compliance under GDPR.', array['legal-ip-contracts']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.6 / SOURCE-ANALYSIS 6.9', 'EU', '[]'::jsonb, 'STABLE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2027-04-05'::date, 180, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-F66
  ('MB-C1', 'Refalco has operational roots in Cyprus going back to the year 2000.', array['company-profile']::text[], 'refalco-commercial', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.0, 3.0 / SOURCE-ANALYSIS 6.1', 'CY', '[{"value":"2000","kind":"year"}]'::jsonb, 'VOLATILE', 'commercial', true, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-C1 [high risk]
  ('MB-C2', 'Refalco has more than 20 years of field experience.', array['company-profile']::text[], 'refalco-commercial', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.0, 3.0 / SOURCE-ANALYSIS 6.1', 'CY', '[{"value":"20 years","kind":"duration"}]'::jsonb, 'VOLATILE', 'commercial', true, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', 'An elapsed time claim drifts on its own, so it is VOLATILE even though the founding year is fixed.'),   -- MB-C2 [high risk]
  ('MB-C3', 'Refalco has delivered 47 real estate development projects.', array['company-profile']::text[], 'refalco-commercial', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.0, 3.0 / SOURCE-ANALYSIS 6.1', 'CY', '[{"value":"47","kind":"count"}]'::jsonb, 'VOLATILE', 'commercial', true, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', 'A project count goes stale as soon as the next project completes.'),   -- MB-C3 [high risk]
  ('MB-C4', 'Refalco has delivered more than 400 multi sector projects.', array['company-profile']::text[], 'refalco-commercial', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.0, 3.0 / SOURCE-ANALYSIS 6.1', 'CY', '[{"value":"400","kind":"count"}]'::jsonb, 'VOLATILE', 'commercial', true, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', 'A project count goes stale as soon as the next project completes.'),   -- MB-C4 [high risk]
  ('MB-C5', 'Refalco is not a narrow company registration office. It positions itself as a gateway to comprehensive investment and structural solutions.', array['company-profile']::text[], 'refalco-commercial', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 2.0, 3.0 / SOURCE-ANALYSIS 6.1', 'CY', '[]'::jsonb, 'VOLATILE', 'commercial', false, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', ''),   -- MB-C5
  ('MB-J0', 'REFAL never attacks another country and never claims Cyprus is always the best. She compares consultatively and analytically, highlighting Cyprus''s structural differences: EU market access, real Substance, and the fusion of investment with residency.', array['jurisdiction-dubai', 'jurisdiction-estonia', 'jurisdiction-malta-bulgaria', 'jurisdiction-usa']::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 3.3 / SOURCE-ANALYSIS 7.4', 'GLOBAL', '[]'::jsonb, 'STABLE', 'explanatory', false, 'BOSS', '2026-10-07'::date, null, '2027-10-07'::date, 365, array['ar', 'en', 'el']::text[], 'approved', 'The posture rule that every jurisdiction comparison is bound by.'),   -- MB-J0
  ('MB-J1', 'Dubai is an excellent environment with no personal income tax, and a Cyprus company is not necessarily a replacement for it. Cyprus adds a direct EU gateway, a European VAT number, and real presence that eases payment gateways and European expansion.', array['jurisdiction-dubai']::text[], 'foreign-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 3.3 / SOURCE-ANALYSIS 7.4', 'AE', '[]'::jsonb, 'VOLATILE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', 'Override: topic is STABLE and explanatory, but this asserts another country''s tax position, which a reviewer must re-verify against that authority.'),   -- MB-J1
  ('MB-J2', 'Estonia is excellent for e Residency and digital solutions but grants no actual residence or property stability and taxes profits at distribution. Cyprus provides a real environment fusing business with residency and property, plus a strong IP Box.', array['jurisdiction-estonia']::text[], 'foreign-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 3.3 / SOURCE-ANALYSIS 7.4', 'EE', '[]'::jsonb, 'VOLATILE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', 'Override: topic is STABLE and explanatory, but taxation at distribution is a foreign tax treatment that needs re-verification.'),   -- MB-J2
  ('MB-J3', 'Bulgaria offers 10% tax but has banking constraints and language and environmental complexity, and Malta runs a complex refund system. Cyprus offers a direct system at 15%, prevalent English, a property market and stable residency.', array['jurisdiction-malta-bulgaria']::text[], 'foreign-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 3.3 / SOURCE-ANALYSIS 7.4', 'EU', '[{"value":"10%","kind":"rate"},{"value":"15%","kind":"rate"}]'::jsonb, 'VOLATILE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', 'Override: topic is STABLE and explanatory, but this row carries two live tax rates. The 15% is the same figure as MB-F19 and must be kept in step with it.'),   -- MB-J3
  ('MB-J4', 'A US LLC or Inc is excellent for e commerce and Stripe sales but brings tax complexity for non residents and gives no direct EU market access.', array['jurisdiction-usa']::text[], 'foreign-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 3.3 / SOURCE-ANALYSIS 7.4', 'US', '[]'::jsonb, 'STABLE', 'explanatory', false, 'BOSS', '2026-10-07'::date, null, '2027-10-07'::date, 365, array['ar', 'en', 'el']::text[], 'approved', 'Kept at the topic''s values: it asserts relative complexity, not a specific rate or rule that can expire.'),   -- MB-J4
  ('MB-DYN1', 'Available properties, unit prices, technical details and current availability are read live from the property database for the specific request and are never stated from memory.', '{}'::text[], 'refalco-commercial', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 5.3 / SOURCE-ANALYSIS 9.4', 'CY', '[]'::jsonb, 'VOLATILE', 'commercial', false, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', 'No owning topic, so volatility and tier are set here: it governs live commercial inventory.'),   -- MB-DYN1
  ('MB-DYN2', 'The reservation deposit amount and conditions are read live from the property database for the specific project and are never stated from memory.', '{}'::text[], 'refalco-commercial', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 5.3 / SOURCE-ANALYSIS 9.4', 'CY', '[]'::jsonb, 'VOLATILE', 'commercial', false, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', 'No owning topic. Pairs with MB-F50, which is the customer facing form of the same prohibition.'),   -- MB-DYN2
  ('MB-DYN3', 'Annual renewal costs for secretary, registered address, accounting, audit and taxes are read live from the corporate pricing source when the customer asks about annual costs, and are never stated from memory.', '{}'::text[], 'refalco-commercial', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 5.3 / SOURCE-ANALYSIS 9.4', 'CY', '[]'::jsonb, 'VOLATILE', 'commercial', false, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', 'No owning topic, so volatility and tier are set here: it governs a published price list.'),   -- MB-DYN3
  ('MB-DYN4', 'Available appointment slots and consultant schedules by timezone are read live from the calendar integration when moving to booking, and are never stated from memory.', '{}'::text[], 'mb-manual', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 5.3 / SOURCE-ANALYSIS 9.4', 'GLOBAL', '[]'::jsonb, 'VOLATILE', 'explanatory', false, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', 'No owning topic. An operational scheduling rule with no commercial or legal figure behind it.'),   -- MB-DYN4
  ('MB-DYN5', 'Government fees, land registry fees and residency application fees are read live from the regulatory rates source when a total deal cost is computed, and are never stated from memory.', '{}'::text[], 'cy-authority', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 5.3 / SOURCE-ANALYSIS 9.4', 'CY', '[]'::jsonb, 'VOLATILE', 'regulated', false, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', 'No owning topic. These are authority set fees, so the tier is regulated.'),   -- MB-DYN5
  ('MB-DYN6', 'Current promotional offers, period discounts and included extras are read live from the offers and pricing table to confirm which offer is actually in force, and are never stated from memory.', '{}'::text[], 'refalco-commercial', 'newplan/Master Brain & Operating Rules Manual - REFAL AI.txt', 'MB 5.3 / SOURCE-ANALYSIS 9.4', 'CY', '[]'::jsonb, 'VOLATILE', 'commercial', false, 'BOSS', '2026-10-07'::date, null, '2026-11-06'::date, 30, array['ar', 'en', 'el']::text[], 'approved', 'No owning topic. This is the rule that keeps the formation package price out of MB-F9 and out of every corpus chunk.')   -- MB-DYN6
-- Re-running this file refreshes what the catalogue owns and leaves the
-- reviewer's own columns alone, so a second run can never un-expire a fact
-- someone retired or revive one they blocked.
on conflict (fact_id) do update set
  claim_text = excluded.claim_text,
  topics = excluded.topics,
  source_type = excluded.source_type,
  source_url_or_document = excluded.source_url_or_document,
  source_ref = excluded.source_ref,
  jurisdiction = excluded.jurisdiction,
  numbers = excluded.numbers,
  volatility = excluded.volatility,
  trust_tier = excluded.trust_tier,
  high_risk = excluded.high_risk,
  notes = excluded.notes;
  -- status, reviewer, verified_at, effective_from, expiry_or_review_at,
  -- review_cadence_days and approved_languages are intentionally untouched.

insert into public.refal_fact_register_audit (fact_id, action, actor, previous, next, reason)
select fact_id, 'seed', 'BOSS', '{}'::jsonb,
       jsonb_build_object('status', status, 'verified_at', verified_at, 'expiry_or_review_at', expiry_or_review_at),
       'Rule 1 seed from the Master Brain manual'
from public.refal_fact_register r
where not exists (
  select 1 from public.refal_fact_register_audit a where a.fact_id = r.fact_id and a.action = 'seed'
);

-- ROLLBACK:
-- delete from public.refal_fact_register_audit where action = 'seed';
-- delete from public.refal_fact_register;
